### ISSUE TITLE
2024-11-12 23:11:02 회고 작성 불가

### ISSUE THREAD

**Issue by tidavid1** [Invincible-Backend-Study/day-day-review#17]
## Log
```
2024/11/12 14:00:16 Error responding with modal: HTTP 400 Bad Request, {"message": "Interaction has already been acknowledged.", "code": 40060}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71d02b]

goroutine 374 [running]:
day-day-review/internal/handler.handleModalSubmit(0xc00013ca88, 0xc00011c7a8)
        /home/ubuntu/day-day-review/internal/handler/handlers.go:40 +0xeb
day-day-review/internal/handler.RegisterInteractions(0xc00013ca88?, 0xc00011c6b0?)
        /home/ubuntu/day-day-review/internal/handler/discord_handlers.go:24 +0x25
github.com/bwmarrin/discordgo.interactionCreateEventHandler.Handle(0x4436db?, 0xc0000a8180?, {0x895340?, 0xc00011c7a8?})
        /home/ubuntu/go/pkg/mod/github.com/bwmarrin/discordgo@v0.28.1/eventhandlers.go:714 +0x33
created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 336
        /home/ubuntu/go/pkg/mod/github.com/bwmarrin/discordgo@v0.28.1/event.go:171 +0x132
```

**Comment by tidavid1** [comment]
@HiiWee @JaeHongDev

**Comment by tidavid1** [comment]
이슈 Close
- 사유: 서버 배포 과정에서 이전 배포가 남아있어 인터렉션이 중복획득되어 발생한 문제. 토큰 재발급으로 해결
